services:
  api:
    build: .
    ports:
      - "8080:8080"
    stop_grace_period: 30s
    environment:
      - PORT=8080
      - DB_ENGINE=postgres
      - DATABASE_URL=host=db user=postgres password=pass dbname=demo port=5432 sslmode=disable
      - JSONPLACEHOLDER_BASE_URL=https://jsonplaceholder.typicode.com
      - RICKANDMORTY_BASE_URL=https://rickandmortyapi.com/api
      - AWS_S3_BUCKET=myawsbucketelito
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
