version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postback_api
    ports:
      - "8000:8000"
    volumes:
      # Mount local directory inside the container for hot-reloading in development
      - .:/app
      # Ignore local .venv to use the container's one
      - /app/.venv
    command: /app/.venv/bin/fastapi run main.py --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    build:
      context: ./deploy/grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
